#!/usr/bin/env bash
# Parses Apache log files in a list format
#  groups visitors by IP and HTTP status
#  displays the no of occurrences IP and HTTP status
#  code of each log, in sorted order
awk '{ print $1 " " $9}' apache-access.log | sort | uniq-c | sort -rn
